services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employee
      - SPRING_DATASOURCE_USERNAME=astro
      - SPRING_DATASOURCE_PASSWORD=astro063
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=astro
      - POSTGRES_PASSWORD=astro063
      - POSTGRES_DB=employee
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data :